SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `beans` (
  `ID` int(11) UNSIGNED NOT NULL COMMENT 'unique ID',
  `date` datetime NOT NULL COMMENT 'date',
  `hours` varchar(4) CHARACTER SET ascii NOT NULL COMMENT 'time logged',
  `tod` varchar(2) CHARACTER SET ascii NOT NULL COMMENT 'time of day',
  `project` varchar(80) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'project worked on',
  `task` varchar(140) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'thing done',
  `category` varchar(40) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'category of activity',
  `comment` varchar(140) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'comments?'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `beans`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `beans`
  MODIFY `ID` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'unique ID', AUTO_INCREMENT=85;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
